const ACTIVITIES = [
  { id:"ACT-001", nombre:"Power BI para Toma de Decisiones", tipo:"Curso", categoria:"Datos y Herramientas", descripcion:"Crea dashboards interactivos y transforma datos en decisiones empresariales con Power BI.", tags:["datos","power_bi","visualizacion","negocios","analitica"], perfiles_recomendados:["D","E","S"], habilidades:["Visualización de datos","Análisis empresarial","Storytelling con datos"], nivel:"Básico-Intermedio", duracion:"4 horas", modalidad:"Presencial", estado:"Activo", cupos:30, oferta_actual:"Baja", emoji:"📊" },
  { id:"ACT-002", nombre:"Excel Avanzado para Negocios", tipo:"Curso", categoria:"Datos y Herramientas", descripcion:"Domina tablas dinámicas, macros y funciones avanzadas para análisis empresarial.", tags:["excel","datos","analitica","herramienta"], perfiles_recomendados:["D","E"], habilidades:["Excel avanzado","Análisis de datos","Automatización básica"], nivel:"Intermedio", duracion:"6 horas", modalidad:"Presencial", estado:"Activo", cupos:25, oferta_actual:"Media", emoji:"📗" },
  { id:"ACT-003", nombre:"Python para Análisis de Datos", tipo:"Taller", categoria:"Datos y Herramientas", descripcion:"Introducción práctica a Python con pandas, matplotlib y numpy para análisis de datos.", tags:["python","datos","programacion","analitica"], perfiles_recomendados:["D","T"], habilidades:["Python","Análisis de datos","Visualización"], nivel:"Básico", duracion:"4 horas", modalidad:"Presencial", estado:"Activo", cupos:20, oferta_actual:"Baja", emoji:"🐍" },
  { id:"ACT-004", nombre:"SQL Empresarial", tipo:"Curso", categoria:"Datos y Herramientas", descripcion:"Aprende a consultar y gestionar bases de datos relacionales con SQL.", tags:["sql","datos","bases_de_datos","programacion"], perfiles_recomendados:["D","T"], habilidades:["SQL","Gestión de datos","Consultas"], nivel:"Básico", duracion:"4 horas", modalidad:"Virtual", estado:"Activo", cupos:30, oferta_actual:"Baja", emoji:"🗄️" },
  { id:"ACT-005", nombre:"IA Aplicada a los Negocios", tipo:"Charla", categoria:"Tecnología e Innovación", descripcion:"Explora cómo la inteligencia artificial está transformando procesos empresariales reales.", tags:["ia","tecnologia","negocios","innovacion","automatizacion"], perfiles_recomendados:["T","E","P"], habilidades:["Comprensión de IA","Pensamiento estratégico","Innovación"], nivel:"Básico", duracion:"2 horas", modalidad:"Presencial", estado:"Activo", cupos:60, oferta_actual:"Media", emoji:"🤖" },
  { id:"ACT-006", nombre:"Automatización de Procesos con IA", tipo:"Taller", categoria:"Tecnología e Innovación", descripcion:"Aprende a identificar y automatizar procesos repetitivos usando herramientas de IA y RPA.", tags:["automatizacion","ia","procesos","eficiencia","tecnologia"], perfiles_recomendados:["T","O","P"], habilidades:["Automatización","Pensamiento de procesos","Herramientas de IA"], nivel:"Intermedio", duracion:"4 horas", modalidad:"Presencial", estado:"Activo", cupos:25, oferta_actual:"Baja", emoji:"⚡" },
  { id:"ACT-007", nombre:"Transformación Digital en Empresas Colombianas", tipo:"Charla", categoria:"Tecnología e Innovación", descripcion:"Casos reales de empresas colombianas que lideraron su transformación digital.", tags:["transformacion_digital","tecnologia","estrategia","innovacion"], perfiles_recomendados:["T","E"], habilidades:["Visión digital","Estrategia de innovación"], nivel:"Básico", duracion:"2 horas", modalidad:"Presencial", estado:"Activo", cupos:80, oferta_actual:"Baja", emoji:"🌐" },
  { id:"ACT-008", nombre:"Negociación Efectiva", tipo:"Taller", categoria:"Habilidades Profesionales", descripcion:"Domina técnicas de negociación basadas en principios, BATNA y comunicación estratégica.", tags:["negociacion","comunicacion","liderazgo","habilidades_profesionales"], perfiles_recomendados:["L","E","S"], habilidades:["Negociación","Comunicación","Pensamiento estratégico"], nivel:"Básico-Intermedio", duracion:"4 horas", modalidad:"Presencial", estado:"Activo", cupos:30, oferta_actual:"Baja", emoji:"🤝" },
  { id:"ACT-009", nombre:"Liderazgo y Equipos de Alto Desempeño", tipo:"Curso", categoria:"Habilidades Profesionales", descripcion:"Desarrolla habilidades de liderazgo, inteligencia emocional y gestión de equipos.", tags:["liderazgo","equipos","comunicacion","habilidades_profesionales"], perfiles_recomendados:["L","P"], habilidades:["Liderazgo","Inteligencia emocional","Comunicación"], nivel:"Básico-Intermedio", duracion:"6 horas", modalidad:"Presencial", estado:"Activo", cupos:25, oferta_actual:"Baja", emoji:"👥" },
  { id:"ACT-010", nombre:"Comunicación y Presentaciones de Impacto", tipo:"Taller", categoria:"Habilidades Profesionales", descripcion:"Aprende a comunicar ideas complejas con claridad y a presentar con confianza.", tags:["comunicacion","presentaciones","liderazgo","habilidades_profesionales"], perfiles_recomendados:["L","E"], habilidades:["Comunicación verbal","Diseño de presentaciones","Hablar en público"], nivel:"Básico", duracion:"3 horas", modalidad:"Presencial", estado:"Activo", cupos:30, oferta_actual:"Media", emoji:"🎤" },
  { id:"ACT-011", nombre:"Gestión de Proyectos con Metodologías Ágiles", tipo:"Curso", categoria:"Habilidades Profesionales", descripcion:"Aprende Scrum, Kanban y PM ágil para liderar proyectos con éxito.", tags:["proyectos","agil","scrum","gestion","liderazgo"], perfiles_recomendados:["P","L","T"], habilidades:["Gestión de proyectos","Agilidad","Liderazgo"], nivel:"Básico-Intermedio", duracion:"6 horas", modalidad:"Presencial", estado:"Activo", cupos:25, oferta_actual:"Baja", emoji:"📋" },
  { id:"ACT-012", nombre:"Lean y Mejora Continua", tipo:"Taller", categoria:"Logística y Operaciones", descripcion:"Aprende los principios de Lean Manufacturing y Kaizen para eliminar desperdicios.", tags:["lean","mejora_continua","procesos","eficiencia","optimizacion"], perfiles_recomendados:["O","S"], habilidades:["Lean thinking","Gestión de procesos","Mejora continua"], nivel:"Básico-Intermedio", duracion:"4 horas", modalidad:"Presencial", estado:"Activo", cupos:30, oferta_actual:"Media", emoji:"⚙️" },
  { id:"ACT-013", nombre:"Simulación de Procesos y Sistemas", tipo:"Curso", categoria:"Logística y Operaciones", descripcion:"Usa simulación para modelar, analizar y optimizar sistemas productivos.", tags:["simulacion","procesos","optimizacion","analitica"], perfiles_recomendados:["O","D"], habilidades:["Simulación","Modelado","Análisis de sistemas"], nivel:"Intermedio", duracion:"8 horas", modalidad:"Presencial", estado:"Activo", cupos:20, oferta_actual:"Baja", emoji:"🎯" },
  { id:"ACT-014", nombre:"Introducción a Supply Chain", tipo:"Charla", categoria:"Supply Chain", descripcion:"Comprende cómo funciona la cadena de suministro global y su impacto en los negocios.", tags:["supply_chain","logistica","distribucion","compras"], perfiles_recomendados:["S","X","O"], habilidades:["Visión de supply chain","Pensamiento sistémico"], nivel:"Básico", duracion:"2 horas", modalidad:"Presencial", estado:"Activo", cupos:70, oferta_actual:"Alta", emoji:"🌍" },
  { id:"ACT-015", nombre:"Gestión de Inventarios y Demanda", tipo:"Curso", categoria:"Supply Chain", descripcion:"Aprende modelos de inventarios, pronóstico de demanda y gestión de stock.", tags:["inventarios","supply_chain","optimizacion","planeacion"], perfiles_recomendados:["S","O","D"], habilidades:["Gestión de inventarios","Pronóstico","Planeación"], nivel:"Intermedio", duracion:"6 horas", modalidad:"Presencial", estado:"Activo", cupos:25, oferta_actual:"Media", emoji:"📦" },
  { id:"ACT-016", nombre:"Compras y Abastecimiento Estratégico", tipo:"Curso", categoria:"Supply Chain", descripcion:"Estrategias modernas de compras, evaluación de proveedores y negociación en supply chain.", tags:["compras","abastecimiento","supply_chain","negociacion","proveedores"], perfiles_recomendados:["S","L"], habilidades:["Compras estratégicas","Negociación","Evaluación de proveedores"], nivel:"Intermedio", duracion:"4 horas", modalidad:"Presencial", estado:"Activo", cupos:25, oferta_actual:"Baja", emoji:"🛒" },
  { id:"ACT-017", nombre:"Visita Empresarial — Centro de Distribución", tipo:"Visita", categoria:"Experiencias Empresariales", descripcion:"Recorre un centro de distribución de clase mundial y observa operaciones logísticas reales.", tags:["visita","logistica","supply_chain","distribucion","experiencia"], perfiles_recomendados:["S","X","O"], habilidades:["Visión operativa","Contexto industrial","Networking"], nivel:"Básico", duracion:"4 horas", modalidad:"Presencial", estado:"Activo", cupos:25, oferta_actual:"Media", emoji:"🏭" },
  { id:"ACT-018", nombre:"Visita Empresarial — Empresa de Tecnología", tipo:"Visita", categoria:"Experiencias Empresariales", descripcion:"Visita una empresa tech colombiana y conoce cómo trabajan sus equipos de datos e innovación.", tags:["visita","tecnologia","innovacion","ia","experiencia"], perfiles_recomendados:["T","X","P"], habilidades:["Visión tecnológica","Networking","Cultura empresarial tech"], nivel:"Básico", duracion:"4 horas", modalidad:"Presencial", estado:"Activo", cupos:25, oferta_actual:"Baja", emoji:"💻" },
  { id:"ACT-019", nombre:"Coffeetalk: Networking con Profesionales de la Industria", tipo:"Evento", categoria:"Experiencias Empresariales", descripcion:"Conecta con profesionales de diferentes sectores en un espacio informal y estructurado de networking uno a uno.", tags:["networking","liderazgo","comunicacion","experiencia","profesionales","marca_empleadora"], perfiles_recomendados:["X","L","P","H","C"], habilidades:["Networking","Comunicación","Construcción de relaciones"], nivel:"Básico", duracion:"3 horas", modalidad:"Presencial", estado:"Activo", cupos:50, oferta_actual:"Baja", emoji:"☕" },
  { id:"ACT-020", nombre:"Reto Empresarial Interdisciplinario", tipo:"Competencia", categoria:"Experiencias Empresariales", descripcion:"Trabaja en equipos multidisciplinarios para resolver un reto real de una empresa patrocinadora con presentación ante jurado.", tags:["reto","casos","innovacion","equipos","experiencia","interdisciplinar","consultoria","casos_empresariales"], perfiles_recomendados:["P","E","X","C"], habilidades:["Trabajo en equipo","Resolución de problemas","Pensamiento creativo","Presentación"], nivel:"Básico-Intermedio", duracion:"8 horas", modalidad:"Presencial", estado:"Activo", cupos:40, oferta_actual:"Baja", emoji:"🏆" },
  { id:"ACT-021", nombre:"Power BI + Supply Chain (Experiencia Combinada)", tipo:"Taller", categoria:"Datos y Herramientas", descripcion:"Aprende a usar Power BI con datos reales de supply chain. Casos prácticos de logística y KPIs operativos.", tags:["power_bi","supply_chain","datos","logistica","analitica","visualizacion"], perfiles_recomendados:["D","S","E","F"], habilidades:["Power BI","Análisis de supply chain","Visualización de KPIs logísticos"], nivel:"Básico-Intermedio", duracion:"6 horas", modalidad:"Presencial", estado:"Activo", cupos:20, oferta_actual:"Baja", emoji:"📊🚚" },
  { id:"ACT-022", nombre:"Caso Empresarial — Análisis de Datos Real", tipo:"Taller", categoria:"Experiencias Empresariales", descripcion:"Resuelve un caso real de una empresa usando datos, herramientas de analítica y presentación estructurada de resultados.", tags:["casos","datos","analitica","practica","empresas","consultoria","diagnostico"], perfiles_recomendados:["D","E","O","C"], habilidades:["Análisis de datos","Pensamiento crítico","Presentación de resultados"], nivel:"Básico-Intermedio", duracion:"5 horas", modalidad:"Presencial", estado:"Activo", cupos:25, oferta_actual:"Baja", emoji:"🔍" },

  /* ── NEW: FINANCE (F) ─── */
  { id:"ACT-023", nombre:"Finanzas para No Financieros", tipo:"Curso", categoria:"Finanzas y Estrategia", descripcion:"Entiende los estados financieros, KPIs clave y cómo se toman decisiones de inversión y rentabilidad en las empresas, sin importar tu carrera.", tags:["finanzas","rentabilidad","costos","presupuesto","roi","valoracion"], perfiles_recomendados:["F","E","C"], habilidades:["Lectura de estados financieros","Análisis de rentabilidad","KPIs financieros"], nivel:"Básico", duracion:"4 horas", modalidad:"Presencial", estado:"Activo", cupos:35, oferta_actual:"Baja", emoji:"💰" },
  { id:"ACT-024", nombre:"Modelación Financiera en Excel", tipo:"Taller", categoria:"Finanzas y Estrategia", descripcion:"Construye modelos financieros en Excel para proyectar flujos de caja, evaluar proyectos de inversión y hacer análisis de sensibilidad.", tags:["finanzas","excel_avanzado","modelacion","rentabilidad","valoracion","datos"], perfiles_recomendados:["F","D","E","C"], habilidades:["Modelación financiera","Excel avanzado","Evaluación de proyectos"], nivel:"Intermedio", duracion:"6 horas", modalidad:"Presencial", estado:"Activo", cupos:20, oferta_actual:"Baja", emoji:"📊💰" },

  /* ── NEW: TALENT & CULTURE (H) ─── */
  { id:"ACT-025", nombre:"Marca Personal y Empleabilidad Profesional", tipo:"Taller", categoria:"Habilidades Profesionales", descripcion:"Desarrolla tu marca personal, aprende a destacar en procesos de selección y construye una presencia profesional auténtica y memorable.", tags:["marca_empleadora","soft_skills","comunicacion","networking","hoja_de_vida","talento"], perfiles_recomendados:["H","L","X","P"], habilidades:["Marca personal","LinkedIn","Entrevistas de trabajo","Comunicación"], nivel:"Básico", duracion:"3 horas", modalidad:"Presencial", estado:"Activo", cupos:30, oferta_actual:"Baja", emoji:"🧠✨" },
  { id:"ACT-026", nombre:"Cultura Organizacional y Liderazgo de Personas", tipo:"Charla", categoria:"Habilidades Profesionales", descripcion:"Charla con líderes de recursos humanos sobre cómo las empresas top en Colombia construyen culturas de alto rendimiento y bienestar.", tags:["cultura_organizacional","talento","bienestar","liderazgo","marca_empleadora"], perfiles_recomendados:["H","L","G"], habilidades:["Gestión del talento","Cultura empresarial","Inteligencia emocional"], nivel:"Básico", duracion:"2 horas", modalidad:"Presencial", estado:"Activo", cupos:60, oferta_actual:"Baja", emoji:"🧠👥" },

  /* ── NEW: SUSTAINABILITY / IMPACT (G) ─── */
  { id:"ACT-027", nombre:"Sostenibilidad Empresarial y Estrategia ESG", tipo:"Charla", categoria:"Sostenibilidad e Impacto", descripcion:"Explora cómo las empresas líderes integran criterios ambientales, sociales y de gobernanza (ESG) en su estrategia y reportes corporativos.", tags:["sostenibilidad","impacto_social","esg","responsabilidad","proposito","estrategia"], perfiles_recomendados:["G","E","C"], habilidades:["Estrategia ESG","Reporte de sostenibilidad","Pensamiento sistémico"], nivel:"Básico", duracion:"2 horas", modalidad:"Presencial", estado:"Activo", cupos:70, oferta_actual:"Baja", emoji:"🌱🌍" },
  { id:"ACT-028", nombre:"Reto de Impacto Social — Innovación con Propósito", tipo:"Competencia", categoria:"Sostenibilidad e Impacto", descripcion:"Diseña una solución empresarial que genere impacto social o ambiental positivo. Presenta ante expertos en innovación social y sostenibilidad.", tags:["impacto_social","sostenibilidad","innovacion","proposito","emprendimiento","reto"], perfiles_recomendados:["G","P","H","E"], habilidades:["Innovación social","Design Thinking","Presentación de proyectos"], nivel:"Básico-Intermedio", duracion:"6 horas", modalidad:"Presencial", estado:"Activo", cupos:30, oferta_actual:"Baja", emoji:"🌱🚀" },

  /* ── NEW: CONSULTING (C) ─── */
  { id:"ACT-029", nombre:"Taller de Consultoría: Diagnóstico y Soluciones Empresariales", tipo:"Taller", categoria:"Consultoría y Estrategia", descripcion:"Aprende el marco metodológico de un consultor: cómo diagnosticar problemas empresariales, estructurar soluciones y comunicar hallazgos a la alta gerencia.", tags:["consultoria","diagnostico","casos_empresariales","estrategia","analitica","presentacion"], perfiles_recomendados:["C","E","D","P"], habilidades:["Metodología de consultoría","Estructuración de problemas","Storytelling ejecutivo"], nivel:"Básico-Intermedio", duracion:"5 horas", modalidad:"Presencial", estado:"Activo", cupos:25, oferta_actual:"Baja", emoji:"🔎📊" }
];

